### PR TITLE
Mb news add new article

### PR DESCRIPTION
**Pull request by meeshysu**
Add article, delete article and edit article all completed.

### CODE REVIEW

**Comment by Rfishernc** [comment]
it worked but then the page froze

**Comment by Rfishernc** [comment]
you are calling the wrong function after adding the article.  You need to call articlecomponent instead of articlePage.  Only thing is that the modal dialog still shows afterwards so you have to manually close it.  Might want to add something to also hide the modal after submitting.

**Comment by meeshysu** [comment]
Marco and I fixed it!! Everything works now. Not sure why it froze?? But the edit refreshes and the modal refreshes as well aka disappears after you add a new article. :) It's fixed now. Should work just fine.

**Comment by MCrank** [comment]
👍 🔞 🦄 🉑

**Comment by Rfishernc** [comment]
👍

**Pull request merged**
